"""posu

Revision ID: 46e4fb5e3d8d
Revises: 9bb7a2e0f6f4
Create Date: 2022-06-23 21:46:44.055613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46e4fb5e3d8d'
down_revision = '9bb7a2e0f6f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.add_column('user', sa.Column('position_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'position', ['position_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'position_id')
    op.drop_table('position')
    # ### end Alembic commands ###
