"""asdf

Revision ID: 9bb7a2e0f6f4
Revises: 
Create Date: 2022-06-23 21:25:14.744734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bb7a2e0f6f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=320), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('firm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.Column('email_address', sa.String(length=80), nullable=False),
    sa.Column('activity_address', sa.String(length=80), nullable=False),
    sa.Column('legal_address', sa.String(length=80), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('hvhh', sa.String(length=120), nullable=True),
    sa.Column('tax_area_code', sa.Integer(), nullable=True),
    sa.Column('chapter_registration_number', sa.Integer(), nullable=True),
    sa.Column('insurer_account_number', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address')
    )
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('firm', sa.Boolean(), nullable=True),
    sa.Column('firm_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('title')
    )
    op.create_table('sphere',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=24), nullable=False),
    sa.Column('last_name', sa.String(length=24), nullable=False),
    sa.Column('email_address', sa.String(length=60), nullable=False),
    sa.Column('image_path', sa.String(length=120), nullable=True),
    sa.Column('ticket', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('ticket')
    )
    op.create_table('user_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_permission')
    op.drop_table('user')
    op.drop_table('sphere')
    op.drop_table('permission')
    op.drop_table('firm')
    op.drop_table('client')
    op.drop_table('auth')
    # ### end Alembic commands ###
